### ISSUE TITLE
EssentialProperties checkbox not limiting A/C properties 

### ISSUE THREAD

**Issue by darrylcn** [Dom2364/PlaneAlerter#16] opened 2022-12-18 23:30 UTC
Hi! I am unable to post on the VRS forum so I registered here. Just wondering if there’s a way to limit the aircraft properties to only those in the essentialProperties.Add list in Core.cs. In 2.4.1 I get emails with properties-Year, Engine_Mount and Air_Pressure for example-which aren’t in the ~17 item list in the essentialProperties. Looks like all the data is being passed from VRS when it shouldn’t(?), and some of it’s bypassing the checkbox setting because it’s present in the feed. 

There is a content difference when selecting All properties and The essentials, so it’s having an impact but not completely limiting to what’s in the essentialProperties list. Hoping it might be limited to just the essentials, unless I’m misunderstanding its use.

**Comment by darrylcn** [comment] 2022-12-20 19:34
I may have found the issue:
Email.cs line 179, 180 has:

179: if (parameter == "UNKNOWN PARAMETER")
180: parameter = propertykey. Tostring();

I think (not sure) that means it’s overriding the unknown it should be using to skip a property, and instead sets it to its real value. 
I changed it to:


if (parameter == "UNKNOWN PARAMETER")
//parameter - propertykey. Tostring() ;
continue;

And now you get essentials when set, and all properties when all properties are set.

**Comment by Dom2364** [comment] 2022-12-21 10:35
Hi, thanks for pointing this out, I'd say the issue is what you've found. For unknown parameters the essentialProperties.Contains check isn't being done at any point so they are shown even if essential properties is selected. Should probably just skip any unknown parameter with essential properties selected. I think that part of the code should be redone anyway since it's a bit messy and hard to understand. I've added it to the list to fix, hopefully I'll get some time to work on Planealerter in the next few weeks.

**Comment by darrylcn** [comment] 2022-12-21 12:55
Sounds good and thanks for the reply. I was worried because I used to chat with you on the VRS forum (I’m darrylcn on there) but that got locked. I messed you on twitter too, at least I think it was you, sorry for going full stalker, you can ignore that DM if you want. Thanks again for all the work you do!

**Comment by Dom2364** [comment] 2022-12-21 13:59
Yeah it's a shame about the forums. That is my Twitter, though the DM has disappeared now for some reason. Thanks for using the program and helping out with this issue!

**Comment by darrylcn** [comment] 2022-12-21 23:31
Happy to help out. It’s good practice for me anyway plus, airplanes,  so yay. Also doesn’t really matter now but the other profile I tried was https://twitter.com/Dominic2364

PM wasn’t open so I tried here, glad it’s a useable forum.

**Comment by Dom2364** [comment] 2023-05-20 07:05
Should be fixed in the latest release (2.5.0)

**Closed as completed by Dom2364** 2023-05-20 07:05 UTC
Labels: bug
